name: Deploy WebGL to GitHub Pages

on:
  push:
    branches:
      - mobile_host

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
